language: python


python: "3.8"


branches:
  only:
    - master


install: pip install -r requirements.txt


script:
  - coverage run --source=envoy -m unittest -v
  - coverage report --fail-under=90


notifications:
  email:
    - sjbitcode@gmail.com
